name: Perl6-Bible
version: 0.24
abstract: Perl 6 Design Documentations
author: Brian Ingerson. All rights reserved.
license: perl
distribution_type: module
requires:
  perl: 5.000
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.44
