name: Perl6-Bible
version: 0.16
abstract: The Gospel according to Cabal
author: Brian Ingerson <ingy@cpan.org>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  Spiffy: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
